### ISSUE TITLE
Major inconsistenty in payload execution order compared to wordlist order inside automate

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#1004]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Automate executes payloads in a different order than the wordlist, causing inconsistency in expected behavior. While expected to a certain degree due to the async nature, the first payloads are near the end of the wordlist.

### How to reproduce

1. Send a request to automate
2. I used [this list](https://gist.githubusercontent.com/danielthall/09b8f173b5c0b84065d8e211def83c0b/raw/20d713765b3fa620c09aebd36e41ce69debef865/0-1000.txt)  
3. Run and see 
### Screenshots:
![image](https://github.com/caido/caido/assets/75004732/4a1a7650-29b3-42a5-b945-6a8ccfeeb4d2)
![image](https://github.com/caido/caido/assets/75004732/6054e365-8324-474f-8900-9475569864fc)

### Environment & setup
OS: Linux
Caido version: 0.36.1

**Comment by Sytten** [comment]
So essentially it depends on two things, the number of workers and the algorithm chosen for the attack.
Right now we prepare all the payloads to send before and then we split then equally between the workers.

So if you have like Matrix with List 1 [1,2,3] and List 2 [4,5,6] it will generate a Result list of [(1,4),(1,5),(1,6),(2,4)...]
Then if you have 4 workers it does Worker 1: Result List[0 to Result List.len() / 4]

I can improve the distribution of tasks so that Worker 1 gets Task 0,4,8 and Worker 2 gets Task 1,5,9

**Comment by Sytten** [comment]
Alright I fixed that for next release
