### ISSUE TITLE
No authentication 

### ISSUE THREAD

**Issue by Aggelos11** [caido/caido#1224]
It would be great if there was not authentication needed each time you want to use the tool . We could just open and use the toold without the whole process of authentication . I do not n think is really needed . Please consider it . Thanks

**Comment by ferasdour** [comment]
Idk, I like that it's just a generic oauth that you can login with google or whatever with. But you mention every time? are you running a new instance every time you run it? because I auth'd once for each device and moved on. Without authentication, you'd be capable of flat running commands on the system at whatever level caido is running, just by hitting the page, and anyone with network visibility to it can do the same.

**Comment by Aggelos11** [comment]
Idk I would like it to be like Burpsuite where you just pull it off and run
and the sign in process can be necessary only for paid versions. It’s just
my opinion. Just keep it in mind

Στις Κυρ 13 Οκτ 2024 στις 5:42 μμ ο χρήστης ferasdour <
***@***.***> έγραψε:

**Comment by Sytten** [comment]
You only need to login once every 3 months. If you have to login every time it means you might reset the instance credentials on launch or something like it.
We are planning an optional guest mode but we won't remove the authentication since we are planning collaboration features that require it.

**Comment by Sytten** [comment]
Closing in favor of #1226

**Comment by Aggelos11** [comment]
When will the guest mode be out ?

Στις Κυρ 13 Οκτ 2024 στις 7:00 μμ ο χρήστης Émile Fugulin <
***@***.***> έγραψε:

**Comment by Sytten** [comment]
We dont give ETA on features, depends on business priorities
