### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Sytten** [caido/caido#2]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allow users to interface with the frontend and backend using custom plugins.

### Use cases

- Add metadata to requests/responses
- Modify requests
- Create special types of attacks

**If you have a use case not listed, please comment so we can build a robust plugin system**

**Comment by agnosticlines** [comment]
I think JavaScript would probably be a better fit, much easier to integrate into Caido given the existing Tauri app, Python support is quite an undertaking and there's going to be a LOT of horrible ugly wrappers for wrapping objects between languages.

**Comment by noraj** [comment]
Burp Suite support extensions in Java, Python and Ruby because Burp Suite in written in Java so they can easily integrate Python with [Jython](https://www.jython.org/) (Python on JVM) and Ruby with [JRuby](https://www.jruby.org/) (Ruby on JVM).

So a similar approach could be taken for Caido that is written in Rust. For example [Artichoke](https://www.artichokeruby.org/) is a Ruby interpreter made with Rust. There is no Rust VM but now there is WASM (WebAssembly). So this can allow integrating Ruby extensions in a Rust app. Same for Python, there is [RustPython](https://rustpython.github.io/), also using WASM.

**Comment by freddd** [comment]
It would be great to be able to write plugins in Rust for those who prefer statically typed languages.

**Comment by Corb3nik** [comment]
Closing this since we now have a plugin system in JavaScript.

The original title for this issue was "Python plugins", but I'm assuming upvotes were mostly about having an actual plugin system, not having a plugin system specifically in Python.
