### ISSUE TITLE
Reorder replay tabs

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#244]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allow users to reorder replay tabs.

**Comment by shriyanss** [comment]
Also, adding a sort feature can be helpful (means sorting by time added, or ascending or descending as per name), which can be reversed (to preserve the order if the user has done any)

In simple words, to toggle between sorted arrangement and manual arrangement

**Comment by Cache-Money** [comment]
Another +1 from me to be able to reorder tabs. This was the first thing I noticed coming from Burp and a major inconvenience since part of my workflow is grouping tabs based on what I'm testing.

**Comment by Sytten** [comment]
We felt is was less pressing since we have collections and you can close them without loosing any data. @Cache-Money

**Comment by Cache-Money** [comment]
Just my opinion on it I think the main thing is when testing functionality that involves replaying 2-3 different tabs, your mouse cursor has to bounce around the screen to go between them. You also need to name them or remember the tab numbers instead of just looking adjacent. That or you close all of your tabs then re-open those 3 from the collection so they are grouped up and you can easily click between them. Also getting used to the position of a certain request and accidentally closing it, then reopening it from the collection and having it get added to the end and stuck there. Being able to reorder the tabs would be great in these situations.

**Comment by Sytten** [comment]
Make sense! I am sure we can prioritize it since it is a smaller task

**Comment by Corb3nik** [comment]
Closing as its done already, but it might be buggy.
