### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#39]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be awesome to have solid keyboard shortcuts for various functions like sending to replay, toggling intercept. If you'd like a list I'd be happy to compile one.

**Comment by Sytten** [comment]
Absolutely! If you have a list we would really appreciate (we also need ideas for sensible defaults for those)!

**Comment by Rhynorater** [comment]
Send to Replay: Ctrl-r
Search within text field: Ctrl-f
Find and Replace within text field: Ctrl-h
Send a request in Replay: Ctrl-Shift-Enter
Duplicate Replay Tab: Ctrl-D
Switch between replay tabs: Ctrl-{ Ctrl-} (Since this is a browser app, we don't want to interfere with browser tab stuff like Ctrl-Tab and Ctrl-Shift-Tab)
Switch to Intercept Tab: _Ctrl-i_
Toggle Intercept: Ctrl-T
Close Replay Tab: Ctrl-W
Re-open Closed Replay Tab: Ctrl-Shift-W


This is everything that I can think of for right now!

**Comment by hakluke** [comment]
I'd suggest using Ctrl-R as the "duplicate replay tab" as well as the "send to replay".

**Comment by 0xatul** [comment]
I'd also suggest adding Ctrl-Shift-v to be used as "Paste URL as request"

**Comment by sw33tLie** [comment]
Nobody used to CTRL+space to send a request?

**Comment by Sytten** [comment]
We started work on shortcuts (CTRL + Z, CTRL + Y in the replay) so it is just a matter of time before we add more :)

**Comment by Corb3nik** [comment]
Implemented so far

- [x] Send to Replay: Ctrl+R
- [x] Search within text field: Ctrl+F
- [x] Find and Replace within text field: Ctrl+H
- [x] Send a request in Replay: Ctrl+Shift+Enter
- [x] Duplicate Replay Tab: Ctrl+R (sams as Send to Replay)
- [ ] Switch between replay tabs: Ctrl-{ Ctrl-} (Since this is a browser app, we don't want to interfere with browser tab stuff like Ctrl-Tab and Ctrl-Shift-Tab)
- [x] Switch to Intercept Tab: Ctrl+I
- [x] Toggle Intercept: Ctrl+P
- [ ] Close Replay Tab: Ctrl+W (Don't want to implement this yet, since we can't restore closed tabs)
- [ ] Re-open Closed Replay Tab: Ctrl+Shift+W
- [ ] Cycle forwards and backward through Replay request state: Ctrl+Alt+RightArrow, Ctrl+Alt+LeftArrow
```

**Comment by Corb3nik** [comment]
Let's track shortcuts in seperate issues: #159, #160, #161
