### ISSUE TITLE
Add filters (httpql) to Intercept

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#580]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Almost every time I queue I get flooded with requests that I don't care about. These are sometimes from other tabs and sometimes unwanted requests from the same app you're testing. An intercepting system based on filters would be really helpful.

**Comment by Sytten** [comment]
Few questions:
- Do you want the filters do be purely visual or do you want automated actions for ignored requests (aka keep them in queue vs drop or forward automatically)
- Would you prefer different filters for responses and requests or something unified for both (since we are adding response interception soon)

**Comment by rluten** [comment]
A good (and maybe simpler) start would be to be able to only intercept requests that are in scope.

**Comment by Sytten** [comment]
Yes we are reworking the intercept page soon and we will be able to add scopes once that is done.
