### ISSUE TITLE
Make the workflows shareable between projects

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#582]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
I always need URL/base64 encoding/decoding in each project so it will be good to add the ability to share them between projects (i.e. make them global) or add some default workflows

### Use cases
Not having to make same workflows each project

**Comment by Sytten** [comment]
Got point, our workflows are JSON based and we plan to allow you to easily copy/paste them to share with colleagues so it should help a bit until we have the full feature. 
Small questions since we are shipping backups of projects for the next release.
Would you expect "global" workflows to be included in the backup of a given project? What behaviour would you expect when restoring this project?

**Comment by hashem-mo** [comment]
Yes, Make them included that would be great actually

**Comment by Rhynorater** [comment]
Big +1 to this.

Ideally, it would be great to have a "Make this as global workflow" checkbox when saving the workflow that would allow you to use it across all projects.

You dont need every workflow on every project, that would be overkill.

**Comment by Corb3nik** [comment]
We could add a tab in the "Workspace" page to manage global workflows, on top of the checkbox to make the workflow "global".

**Comment by ly4e** [comment]
also plus one to this idea and would like to apply the ability to have some other items also able to be "globally scoped/visible" OR only scoped/visible to the project they were created in.

and yes anything global i would enjoy having in the backup so that it ensures that a restore would be less likely to be missing a critical piece.
