### ISSUE TITLE
"Unexpected failure when reading response" when sending edited request

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#740]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When intercepting + editing a request in the `Cookies` challenge of picoCTF, Caido is unable to get the response.

![image](https://github.com/caido/caido/assets/6225588/2a41409b-9864-4d17-b8e5-3d5422aaf064)

Looking at Wireshark, it seems like the TCP connection is closed before ever receiving a single byte from the server.

### How to reproduce

- Create a picoCTF account
- Go to https://play.picoctf.org/practice/challenge/173?page=1&search=Cookies
- Visit the link of the Cookies challenge
- Start intercepting with Caido and hit the "Search" button
- Edit the intercepted request and send it.

**Comment by Sytten** [comment]
This seems to be due to the fact that caido is opening connections early and keep them pending if the request is paused. 

This particular server seems to kill off idle connections at the application layer very fast. It is likely an aggressive read timeout in the HTTP code, which is typical for services that are sync and where each connection is handled by a thread/process. 

We tried some keep alive at the TCP layer without success. Further confirming the application layer timeout.

We need to change when we open the upstream connection after the intercept, just before we are ready to send. It should not be too hard, but some logic need to change to accommodate that.

One would be to introduce a timeout on our application inbound HTTP processing, right now it is only dependant on the target service closing the connection.

Once we introduce websocket interception, we will need to drive ping/pong messages to avoid the connection being killed even if a user decided to pause.
